### ISSUE TITLE
[BUG]: UI hover issue

### ISSUE THREAD

**Issue by Auxtal** [AykutSarac/jsoncrack.com#236] opened 2022-10-11 03:03 UTC
### Issue description

As you can see when hovering over a "connection" only the line is effected by the hover state and not the arrow head, I know it's a very small thing but it's there and somewhat noticeable.

<img width="379" alt="Screen Shot 2022-10-11 at 11 00 56 am" src="https://user-images.githubusercontent.com/69879926/194987282-bef5014c-78b4-40f9-b9ab-0f2e72576e6f.png">

### Operating system

- OS: MacOS Monterey 12.6
- Browser: Chrome

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment] 2022-10-30 10:55
Actually that's not a bug, but something that can be added as a feature.

> Hi! Could I please take this issue? Thanks

Sure, appreciate it!

**Comment by JStuve** [comment] 2023-02-05 16:57
Came to a conclusion that this was not possible through JSON Crack and had to be resolved in Reaflow library. See the open PR above for more details and a solution to this issue.

**Closed** 2023-03-08 08:34 UTC
Labels: feature, confirmed
