### ISSUE TITLE
Bug: It is not formatting terraform state file

### ISSUE THREAD

**Issue by mohan023** [AykutSarac/jsoncrack.com#153] opened 2022-09-10 06:23 UTC
### Issue description

The state file contains around 7000 of lines. 
![image](https://user-images.githubusercontent.com/4489345/189471944-953adc03-7205-4b61-b82c-4df6689ee110.png)

### Operating system

- OS: [e.g. iOS]: OS
- Browser [e.g. chrome, safari]: Chrome

- Any other details...

### Priority this issue should have

High (immediate attention needed)

**Comment by AykutSarac** [comment] 2022-09-10 07:24
You should wait a bit longer than usual while the canvas is rendering when the file is big.

**Comment by alicashelton** [comment] 2022-09-10 18:44
Ok, let's wait

**Comment by mohan023** [comment] 2022-09-10 20:07
I waited for 15 mins. But it didn't work. There is no progress bar so that
we know if we should wait more or there is a problem.

**Comment by AykutSarac** [comment] 2022-09-10 20:12
Can you share the json file?

**Comment by mohan023** [comment] 2022-09-10 20:33
There is some sensitive data in file. I cannot modify it manually. So I
would not be able to share it.

**Comment by AykutSarac** [comment] 2022-09-11 19:43
Can you share more details about your OS & specs? Also can you try again, I made some improvements today?

**Comment by mohan023** [comment] 2022-09-12 03:20
Os is Windows. Browser is chrome. Processor i5. Sure I'll try again today.

**Comment by AykutSarac** [comment] 2022-10-30 11:06
Assuming the issue is has been resolved now, closing it.

**Closed by AykutSarac** 2022-10-30 11:06 UTC
Labels: bug

**Comment by mohan023** [comment] 2022-10-30 14:07
Sure.
