### ISSUE TITLE
Large numbers conversion to BigInt error

### ISSUE THREAD

**Issue by pavelsaman** [AykutSarac/jsoncrack.com#79] opened 2022-08-06 19:31 UTC
This JSON seems valid according to https://jsonlint.com/ and https://www.json.org/json-en.html:

```json
{
    "largeNumer": 2.5e50
}
```

JSON Visio tries to convert it to BigInt and it fails:

```
SyntaxError: Cannot convert 05+e5 to a BigInt (at _app-3f3d54d5d6e3969c.js:1:48888)
    at BigInt (<anonymous>)
    at l (_app-3f3d54d5d6e3969c.js:1:48888)
    at Object.t [as num_to_s] (_app-3f3d54d5d6e3969c.js:1:49142)
    at e.encodeNum (_app-3f3d54d5d6e3969c.js:1:45639)
    at l (_app-3f3d54d5d6e3969c.js:1:47629)
    at Object.l [as addValue] (_app-3f3d54d5d6e3969c.js:1:47535)
    at e.compress (_app-3f3d54d5d6e3969c.js:1:45152)
    at Editor-1addf083bf22d274.js:1:20846
    at ei (framework-0471df08d5fed370.js:1:94315)
    at ws (framework-0471df08d5fed370.js:1:114733)
    at framework-0471df08d5fed370.js:1:113468
    at ks (framework-0471df08d5fed370.js:1:113534)
    at us (framework-0471df08d5fed370.js:1:107308)
    at jl (framework-0471df08d5fed370.js:1:47918)
    at framework-0471df08d5fed370.js:1:104703
```

![image](https://user-images.githubusercontent.com/24702416/183263479-5eee9328-033e-4f55-852a-b058c394377b.png)

I'd argue that keeping the number displayed with the exponent (`e50`) would be just fine since that's an allowed JSON number format.

**Comment by AykutSarac** [comment] 2022-08-07 09:27
Looks like the issue is triggered by compression library.

**Comment by pavelsaman** [comment] 2022-08-08 06:45
> Looks like the issue is triggered by compression library.

Possibly. There might be related tiny problems with strings, especially with escaped characters like: `\n`, `\r`, `\/`, and similar https://www.json.org/img/string.png

**Comment by AykutSarac** [comment] 2022-08-19 12:50
Should be fixed with #91

**Comment by sbres** [comment] 2022-08-31 09:48
I'm having the same problem with the json as a one-liner and post processed from jsonformatter.org/json-pretty-print 
I'm having the break with a not so big value
```
1.98653973e-9
```

**Comment by kaungsithar** [comment] 2022-09-11 19:09
> I'm having the same problem with the json as a one-liner and post processed from jsonformatter.org/json-pretty-print I'm having the break with a not so big value
> 
> ```
> 1.98653973e-9
> ```

It seems to be working now. Following is a screenshot with number as you mentioned.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/41876358/189544798-39344179-283c-406f-8e17-c79c0c12003d.png">

**Closed** 2022-09-11 19:24 UTC
Labels: bug
