### ISSUE TITLE
[BUG]: JSON array of objects not displayed in correct order

### ISSUE THREAD

**Issue by mitjaahlin** [AykutSarac/jsoncrack.com#207] opened 2022-09-27 06:59 UTC
### Issue description

As already said in the title... It's not a big deal, just annoying and not so useful for array of object, as it is not sorted the same as in JSON.

### Media & Screenshots

![image](https://user-images.githubusercontent.com/26851656/192455691-b67e99a5-d826-48c9-a1ee-2b0d1f9ac500.png)

### Priority this issue should have

Low (slightly annoying)

**Comment by Sandyacvedo** [comment] 2022-10-01 14:42
Hi, Can I work on this issue and create a PR ?

**Comment by AykutSarac** [comment] 2022-10-01 15:00
> Hi, Can I work on this issue and create a PR ?

Sure, but please refrain from making direct solutions like checking if it'a an array of numberd and if so using .sort().

**Comment by eLeontev** [comment] 2022-10-03 08:28
I digged a bit in the code and based on my research the issue is at `Canvas` component side, so the issue might be derected to `reaflow` repo instead of this on. 

In another hand Canvas has applied a lot of layout options and in case if project has configuration it may be fixed by the configuration, but I did not investigate it

My research results:
- use test json `[1,2,3,4]`
- check nodes order - it's correct
- check nodes calculated position - it's incorrect passed from `reaflow`

**Comment by Vishal-Isharani** [comment] 2022-11-05 06:45
@eLeontev yes you are right it's a reaflow issue I have verified that https://github.com/reaviz/reaflow/issues/92#issuecomment-1304420301.

**Closed** 2023-01-06 20:33 UTC
Labels: bug, confirmed
