### ISSUE TITLE
Extension for Jetbrains

### ISSUE THREAD

**Issue by re3factor** [AykutSarac/jsoncrack.com#323] opened 2023-03-22 23:07 UTC
### Feature

Not a VS Code user so I figured I would just ask if you could make an extension for JetBrains IDEs

**Comment by i-am-unknown-81514525** [comment] 2023-04-25 17:48
Agreed, it would be extremely helpful

**Comment by wuguangping** [comment] 2023-05-26 03:59
+1

**Comment by AntonShuvaev** [comment] 2023-08-13 14:37
Take a look at this plugin https://plugins.jetbrains.com/plugin/22472-datagraph--json-yaml-xml-visualization

**Comment by i-am-unknown-81514525** [comment] 2023-08-13 14:48
It require £1.5/year which not very helpful as it requires me to pay to use it

**Comment by mamachnik** [comment] 2023-08-25 06:43
duplicate of #269 but still it would be nice too see a JetBrains plugin.

**Comment by mamachnik** [comment] 2024-01-08 12:13
https://github.com/AykutSarac/jsoncrack.com/issues/344#issue-1811866371 seems to be a promising solution @wuguangping @i-am-unknown-81514525 @re3factor

**Comment by AykutSarac** [comment] 2024-12-07 07:09
Closing as duplicate of #269

**Closed by AykutSarac** 2024-12-07 07:09 UTC
Labels: feature
